project:
  type: website
  output-dir: docs

website:
  title: "Field Research Centre Hasselt University"
  description: This is the website of the Field Research Centre of Hasselt University Centre for Environmental Sciences.
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - people.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true



