project:
  type: website
  output-dir: docs
  resources: 
  - "google236138b44c78c86c.html"

website:
  title: "Field Research Centre Hasselt University"
  description: This is the website of the Field Research Centre of Hasselt University Centre for Environmental Sciences.
  site-url: "https://frc-community-ecology.github.io/"
  site-path: '/'
  
  navbar:
    left:
      - research.qmd
      - people.qmd
      - news.qmd
      - publications.qmd
      - contact.qmd
      
  page-footer:
    center: "**Field Research Centre** <br>
    Hasselt University | Centre for Environmental Sciences <br>
    <br>
    Website by Imke Tomsin <br>
    Last updated: October 2026"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    anchor-sections: false
    toc: true

