project:
  type: website
  output-dir: docs

website:
  title: "Field Research Centre Hasselt University"
  description: This is the website of the Field Research Centre of Hasselt University Centre for Environmental Sciences.
  navbar:
    left:
      - research.qmd
      - people.qmd
      - news.qmd
      - publications.qmd
      - contact.qmd
      
  page-footer:
    center: "**Field Research Centre** <br>
    Hasselt University | Centre for Environmental Sciences <br>
    <br>
    Last updated: September 2026"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    anchor-sections: false
    toc: true

